sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 192.168.0.46
    port: 3306
    database: sky_take_out
    username: root
    password: =]-[0p9o8i

  redis:
    host: 192.168.0.46
    port: 6379
    password: =]-[0p9o8i
    database: 0
  wechat:
    appid: wx43074a5173417496
    secret: b7e01a27f3e8b4c287a5e6067f6554bb